name: Deploy to Render

on:
  # This workflow will run when a tag is pushed to the repository
  push:
    tags:
      - 'v*'  # Trigger the workflow on tags that start with 'v' (e.g., v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Check out the code from the repository

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # API key for Render, stored in GitHub Secrets
      run: |
        # Authenticate with Render API
        curl -X POST "https://api.render.com/v1/services/your-service-id/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"branch": "main"}'  # Trigger deployment for the main branch
